from enum import StrEnum


class RoleName(StrEnum):
    STUDENT = "STUDENT"
    LECTURER = "LECTURER"
    ENROLMENT_OFFICER = "ENROLMENT_OFFICER"
    CREDIT_MAPPING_OFFICER = "CREDIT_MAPPING_OFFICER"
    ADMINISTRATOR = "ADMINISTRATOR"


class InstitutionType(StrEnum):
    UNIVERSITY = "UNIVERSITY"
    COLLEGE = "COLLEGE"
    VOCATIONAL = "VOCATIONAL"
    OTHER = "OTHER"


class StudentStatus(StrEnum):
    PROSPECTIVE = "PROSPECTIVE"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    COMPLETED = "COMPLETED"
    WITHDRAWN = "WITHDRAWN"


class CreditSystem(StrEnum):
    AU_CREDIT_POINTS = "AU_CREDIT_POINTS"
    ECTS = "ECTS"
    US_CREDIT_HOURS = "US_CREDIT_HOURS"
    UK_CREDITS = "UK_CREDITS"


class EnrolmentApplicationStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ExternalProfileType(StrEnum):
    LINKEDIN = "LINKEDIN"
    PORTFOLIO = "PORTFOLIO"
    PROFESSIONAL_PROFILE = "PROFESSIONAL_PROFILE"
    OTHER = "OTHER"


class StudentDocumentType(StrEnum):
    TRANSCRIPT = "TRANSCRIPT"
    CERTIFICATE = "CERTIFICATE"
    COURSE_OUTLINE = "COURSE_OUTLINE"
    ACADEMIC_RECORD = "ACADEMIC_RECORD"
    IDENTIFICATION = "IDENTIFICATION"
    EMPLOYMENT_EVIDENCE = "EMPLOYMENT_EVIDENCE"
    PROFESSIONAL_CERTIFICATE = "PROFESSIONAL_CERTIFICATE"
    OTHER = "OTHER"


class StudentDocumentStatus(StrEnum):
    PENDING = "PENDING"
    QUARANTINED = "QUARANTINED"
    CLEAN = "CLEAN"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class CreditMappingRequestStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class CreditMappingDecisionValue(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
